# Generated by Django 5.0.4 on 2024-05-10 13:50

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('New Business', 'New Business'), ('Suspended Business', 'New Business'), ('Activated Business', 'Activated Business')], default='New Business', max_length=30, unique=True)),
                ('subject', models.CharField(max_length=100)),
                ('message', tinymce.models.HTMLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
